export const COLLECTIONS = {
  services: {
    title: "Services",
    endpoint: "services",
    label: "service",
    columns: [
      { key: "title", label: "Title" },
      { key: "summary", label: "Summary" },
      { key: "order", label: "Order" },
    ],
    fields: [
      { key: "title", label: "Title" },
      { key: "slug", label: "Slug (optional)", help: "Auto-generated if left blank" },
      { key: "summary", label: "Summary", type: "textarea" },
      { key: "description", label: "Description", type: "textarea" },
      { key: "icon", label: "Icon (lucide name)", help: "e.g. layout, search, shield" },
      { key: "features", label: "Features", type: "tags" },
      { key: "order", label: "Order", type: "number" },
    ],
    defaults: { title: "", summary: "", description: "", icon: "sparkles", features: [], order: 99 },
  },

  portfolio: {
    title: "Portfolio",
    endpoint: "portfolio",
    label: "project",
    columns: [
      { key: "title", label: "Title" },
      { key: "industry", label: "Industry" },
      { key: "featured", label: "Featured", type: "boolean" },
    ],
    fields: [
      { key: "title", label: "Title" },
      { key: "slug", label: "Slug (optional)" },
      { key: "client", label: "Client" },
      { key: "industry", label: "Industry" },
      { key: "featured", label: "Featured on homepage", type: "boolean" },
      { key: "order", label: "Order", type: "number" },
      { key: "cover", label: "Cover image", type: "image" },
      { key: "categories", label: "Categories", type: "tags" },
      { key: "tags", label: "Tags", type: "tags" },
      { key: "technologies", label: "Technologies", type: "tags" },
      { key: "live_url", label: "Live URL" },
      { key: "overview", label: "Overview", type: "textarea" },
      { key: "problem", label: "The Problem", type: "textarea" },
      { key: "solution", label: "The Solution", type: "textarea" },
      { key: "process", label: "Process", type: "textarea" },
      { key: "results", label: "Results", type: "objectlist", subfields: [ { key: "value", label: "Value" }, { key: "label", label: "Label" } ] },
      { key: "gallery", label: "Gallery", type: "gallery" },
    ],
    defaults: { title: "", client: "", industry: "", featured: false, order: 99, cover: "", categories: [], tags: [], technologies: [], live_url: "", overview: "", problem: "", solution: "", process: "", results: [], gallery: [] },
  },

  "case-studies": {
    title: "Case Studies",
    endpoint: "case-studies",
    label: "case study",
    columns: [
      { key: "title", label: "Title" },
      { key: "client", label: "Client" },
      { key: "featured", label: "Featured", type: "boolean" },
    ],
    fields: [
      { key: "title", label: "Title" },
      { key: "slug", label: "Slug (optional)" },
      { key: "client", label: "Client" },
      { key: "industry", label: "Industry" },
      { key: "featured", label: "Featured", type: "boolean" },
      { key: "order", label: "Order", type: "number" },
      { key: "cover", label: "Cover image", type: "image" },
      { key: "summary", label: "Summary", type: "textarea" },
      { key: "challenge", label: "The Challenge", type: "richtext" },
      { key: "solution", label: "The Solution", type: "richtext" },
      { key: "process", label: "Process", type: "richtext" },
      { key: "before_image", label: "Before image", type: "image" },
      { key: "after_image", label: "After image", type: "image" },
      { key: "results", label: "Results", type: "objectlist", subfields: [ { key: "value", label: "Value" }, { key: "label", label: "Label" } ] },
      { key: "gallery", label: "Gallery", type: "gallery" },
      { key: "seo", label: "SEO", type: "objectgroup", subfields: [ { key: "meta_title", label: "Meta title" }, { key: "meta_description", label: "Meta description", type: "textarea" } ] },
    ],
    defaults: { title: "", client: "", industry: "", featured: false, order: 99, cover: "", summary: "", challenge: "", solution: "", process: "", before_image: "", after_image: "", results: [], gallery: [], seo: {} },
  },

  blog: {
    title: "Blog",
    endpoint: "posts",
    label: "article",
    columns: [
      { key: "title", label: "Title" },
      { key: "category", label: "Category" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "title", label: "Title" },
      { key: "slug", label: "Slug (optional)" },
      { key: "category", label: "Category" },
      { key: "author", label: "Author" },
      { key: "status", label: "Status", type: "select", options: ["draft", "published"] },
      { key: "featured", label: "Featured", type: "boolean" },
      { key: "read_time", label: "Read time (min)", type: "number" },
      { key: "cover", label: "Featured image", type: "image" },
      { key: "tags", label: "Tags", type: "tags" },
      { key: "excerpt", label: "Excerpt", type: "textarea" },
      { key: "content", label: "Content", type: "richtext", help: "Separate paragraphs with a blank line." },
      { key: "published_at", label: "Publish date (ISO)", help: "e.g. 2025-01-15T09:00:00Z — used for scheduling/ordering" },
      { key: "seo", label: "SEO", type: "objectgroup", subfields: [ { key: "meta_title", label: "Meta title" }, { key: "meta_description", label: "Meta description", type: "textarea" } ] },
    ],
    defaults: { title: "", category: "Design", author: "Studio Admin", status: "draft", featured: false, read_time: 5, cover: "", tags: [], excerpt: "", content: "", published_at: "", seo: {} },
    listQuery: "?admin=1",
  },

  testimonials: {
    title: "Testimonials",
    endpoint: "testimonials",
    label: "testimonial",
    slugless: true,
    columns: [
      { key: "name", label: "Name" },
      { key: "company", label: "Company" },
      { key: "featured", label: "Featured", type: "boolean" },
    ],
    fields: [
      { key: "quote", label: "Quote", type: "textarea" },
      { key: "name", label: "Name" },
      { key: "role", label: "Role" },
      { key: "company", label: "Company" },
      { key: "avatar", label: "Avatar", type: "image" },
      { key: "featured", label: "Featured on homepage", type: "boolean" },
      { key: "order", label: "Order", type: "number" },
    ],
    defaults: { quote: "", name: "", role: "", company: "", avatar: "", featured: false, order: 99 },
  },

  faqs: {
    title: "FAQs",
    endpoint: "faqs",
    label: "FAQ",
    slugless: true,
    columns: [
      { key: "question", label: "Question" },
      { key: "order", label: "Order" },
    ],
    fields: [
      { key: "question", label: "Question" },
      { key: "answer", label: "Answer", type: "textarea" },
      { key: "order", label: "Order", type: "number" },
    ],
    defaults: { question: "", answer: "", order: 99 },
  },
};
